### ISSUE TITLE
Обратная связь

### ISSUE THREAD

**Issue by AndreyLyamkin** [tarasifua/vvip-68-matrix-home-assistant-integration#1]
Прикрутил к своему НА. Работает.
А может сделать полную интеграцию с гирляндой? Сейчас, если изменить параметр из приложения, то в интерфейсе Home Assistant ничего не меняется. Что не совсем удобно. Да при перезапуске НА не происходит чтения всех действующих параметров

**Comment by tarasifua** [comment]
Там и есть полная интеграция. При изменении параметра в приложении он меняется в HA. Если у вас не так, значит что-то неправильно настроили. Пакетный режим передачи параметров выключен в прошивке?

https://user-images.githubusercontent.com/1798483/103204005-06a0e480-48ff-11eb-8d30-d2154c013685.mov

**Comment by AndreyLyamkin** [comment]
Странно. Пересыльное прошивку. Попробую. У меня пока только управляет. А вот назад никак. Видимо ошибка на моей стороне.

**Comment by tarasifua** [comment]
Установите MQTT Explorer на комп и посмотрите в каком виде гирлянда шлет данные на MQTT сервер.

**Comment by AndreyLyamkin** [comment]
> Пакетный режим передачи параметров выключен в прошивке?
Так он должен быть выключен?
Как выключить?
брокеру прилетает все подряд в топик "stt"
отправил в "cmd" -> $11 6 0 и все заработало... почти все.. пока что не разобрался, почему режимы гирлянды не синхронизируются

**Comment by tarasifua** [comment]
> отправил в "cmd" -> $11 6 0 и все заработало... почти все.. пока что не разобрался, почему режимы гирлянды не синхронизируются

 Можно и так, или как написано в Readme: `файл a_def_soft.h, переменная bool mqttstatepacket = false;`

Режимы? настройки режима считываются после выбора его в выпадающем списке. А если включен авторежим, там автоматом выберется пункт "---------". Тоесть во время авторежима они в выпадающем списке сами переключаться не будут. Это не баг, так и должно быть

**Comment by AndreyLyamkin** [comment]
> > отправил в "cmd" -> $11 6 0 и все заработало... почти все.. пока что не разобрался, почему режимы гирлянды не синхронизируются
> 
> Режимы? настройки режима считываются после выбора его в выпадающем списке. А если включен авторежим, там автоматом выберется пункт "---------". Тоесть во время авторежима они в выпадающем списке сами переключаться не будут. Это не баг, так и должно быть

Было бы намного информативнее, если бы текущий эффект отображался на странице НА. Может добавить тогда просто строку с текущим эффектом? У меня была цель видеть на телефоне через мобильное приложение НА, какой режим сейчас воспроизводит гирлянда.

**Comment by tarasifua** [comment]
> Может добавить тогда просто строку с текущим эффектом?

Да в принципе элементарно. Создаем mqtt sensor:
```yaml
  - platform: mqtt
    name: "Поточний ефект"
    state_topic: "WiFiPanel-0/stt/EN"
```
И суем его в любое место в `lovelace-ui.yaml` по надобности.
Если что, в репозиторий добавил
